Structs
dadosjusbr/executor pull request #1
Opened 2020-06-09 20:39 UTC by Lorenaps

- Criando a lib
- Criando as structs
- Adicionando a assinatura da função Run.

2020-06-09 20:52 UTC, danielfireman requested changes

2020-06-09 20:52 UTC, danielfireman commented on .env.example
> +COLLECTOR_DIR_LIST=/trt13,/mppb
Não acho que iremos precisar de variáveis de ambiente. Estamos criando uma biblioteca e o mais comum (e claro) é ter as configurações passadas como parâmetro.

2020-06-09 20:52 UTC, danielfireman commented on main.go
> +	//ler .env
Não iremos ter um main, iremos ter uma lib.

2020-06-09 20:52 UTC, danielfireman commented on pipeline/go.mod
> +module github.com/dadosjusbr/executor/pipeline
A raíz do módulo (coisa que será importada pelo alba) deve ser a raíz do repo. Isso torna as coisas mais simples.

2020-06-09 20:52 UTC, danielfireman commented on pipeline/run.go
> +func Run(pipeline Pipeline) ([]storage.ProcInfo, error) {
Não gostaria que você importasse o storage. É uma dependência que ealmente não precisamos. Poderia, por favor, copiar e colar aqui? (lembrando que não necessariamente precisamos das struct tags do mongo)

Pode chamar de `StageExecutionResult`

2020-06-09 20:52 UTC, danielfireman commented on pipeline/run.go
> +	Dir  string
Repo?

2020-06-09 20:52 UTC, danielfireman commented on pipeline/run.go
> +type Env struct {
Essas variáveis são específicas de cada estágio e o executor não deve saber detalhes de cada estágio. `Env` deve ser um `map[string]string`

2020-06-09 20:52 UTC, danielfireman commented on pipeline/run.go
> +	Envs   Env
`Env map[string]string`

2020-06-09 20:58 UTC, Lorenaps commented on .env.example
> +COLLECTOR_DIR_LIST=/trt13,/mppb
Eu concordo contigo.
Adicionei aí por conta  do que conversamos de ter um main onde as pessoas interessadas pudessem executar. Entendi que ele seria dentro do repositório. 
Mas vou retirar e deixar apenas a passagem por parâmetro mesmo.

2020-06-09 20:59 UTC, Lorenaps commented on pipeline/run.go
> +type Env struct {
Certo.

2020-06-09 21:02 UTC, Lorenaps commented on pipeline/run.go
> +	Dir  string
O repo, que chamamos de path no Alba, estaria mapeado no Path do Pipeline.
A aplicação desse dir seria para a os estágios packager e store.

2020-06-09 21:03 UTC, Lorenaps commented on pipeline/run.go
> +func Run(pipeline Pipeline) ([]storage.ProcInfo, error) {
Posso sim. Vou ajustar.

2020-06-09 21:04 UTC, Lorenaps commented on pipeline/go.mod
> +module github.com/dadosjusbr/executor/pipeline
Certo.

2020-06-09 21:05 UTC, Lorenaps commented on pipeline/run.go
> +	Envs   Env
Certo.

2020-06-09 21:10 UTC, danielfireman commented on pipeline/run.go
> +	Dir  string
Tinha entendido completamente o contrário sobre o repo no Alba, acredita? Puxa! hahaha Pensei que você não tinha gostado da ideia de usar o esquema de imports de Go. 

De toda forma, a coisa está nascendo ainda e podemos mudar. Uma especificação que me parece bem simples é que a usamos no último papo: cada estágio pode ter um `Repo` (opcional) e o pipeline pode ter um `DefaultRepo`. Daí, caso a pessoa não queira, não precisa ficar setando cada um dos repos. O `Dir` também é opcional e caso não esteja setado usamos o `Name`, que é o único campo realmente obrigatório de cada estágio :smile: 

Um comportamento comum é o repo mais específico (do estágio) sobrescreve o geral (default) caso esteja setado e caso nenhum dos dois esteja setado o pipeline não deve executar. 

O que acha?

2020-06-11 20:08 UTC, Lorenaps commented on pipeline/run.go
> +	Dir  string
Concordo. Acho que no `Stage` só vale manter a variável `Name` se o objeitvo dela for armazenar um nome diferente do diretório, talvez para para tornar o retorno das etapas mais inteligível, customizável... Mas se encarmos ela como obrigatória e que seu valor deve ser o mesmo nome do diretório é melhor chamar apenas de `Dir` mesmo. Faz sentido?
Atualizei para: 
- Name string
- Dir  string
- Repo string
- Envs map[string]string

2020-06-12 13:26 UTC, danielfireman approved these changes
Poderia dar uma olhada nos comentários abaixo, por favor?

2020-06-12 13:26 UTC, danielfireman commented on pipeline.go
> +	DefaultRepo string
Adicionar `DefaultEnv`?

2020-06-12 13:26 UTC, danielfireman commented on pipeline.go
> +	Envs map[string]string
```suggestion
	Env map[string]string
```

2020-06-12 13:26 UTC, danielfireman commented on go.mod
> +require github.com/dadosjusbr/storage v0.0.0-20200610184129-9f957c447914
Vocẽ não depende de `dadosjusbr/storage` mais. Essa dependência está errada.

Pode rodar um `go mod tidy` por favor?

2020-06-12 18:07 UTC, Lorenaps commented on pipeline.go
> +	DefaultRepo string
Certo.

2020-06-12 18:08 UTC, Lorenaps commented on pipeline.go
> +	Envs map[string]string
Certo.

2020-06-12 18:12 UTC, Lorenaps commented on go.mod
> +require github.com/dadosjusbr/storage v0.0.0-20200610184129-9f957c447914
Sim. Eu fiz isso mas acabei não subindo.
Acabei de atualizar.

2020-06-12 18:14 UTC, merged