Usando a lib status no estágio em Go
dadosjusbr/executor pull request #22
Opened 2020-08-13 23:13 UTC by Lorenaps

- Trazendo os demais arquivos do pacote status
- Usando o pacote no stage-go

2020-08-19 13:50 UTC, danielfireman requested changes
Massa!

Acho apenas que está faltando inicializar o módulo dentro de stage-go (expliquei melhor via slack). Como mencionei no comentário abaixo, não precisa fazer `go get`

2020-08-19 13:50 UTC, danielfireman commented on tutorial/stage-go/Dockerfile
> +RUN apk update && apk add git && go get "github.com/dadosjusbr/executor"
Não precisa fazer go get.

2020-08-21 17:51 UTC, Lorenaps commented on tutorial/stage-go/Dockerfile
> +RUN apk update && apk add git && go get "github.com/dadosjusbr/executor"
Certo. Atualizei a partir da conversa que tivemos no slack. Obrigada.

2020-08-21 17:54 UTC, danielfireman approved these changes

2020-08-24 14:55 UTC, merged