Add result pipeline
dadosjusbr/executor pull request #8
Opened 2020-07-10 23:54 UTC by Lorenaps

2020-07-13 20:13 UTC, Lorenaps commented on pipeline.go
> +		if err := buildImage(id, dir, stage.BuildEnv, &ser.BuildResult); err != nil {
Fiz uma alteração em como os resultados são salvos nas funções build e run. Gostaria de ver contigo se existe alguma recomendação ou regra para a utilização de passagem por referência em go.

2020-07-14 12:02 UTC, danielfireman requested changes

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +	StageResult []StageExecutionResult `json:"stageResult" bson:"stageResult,omitempty"` // Results of stage execution.
[sugestão] `StageResults`? Note o `s` no final :)

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +	Timestamp   int64                  `json:"timestamp" bson:"timestamp,omitempty"`     // Timestamp of pipeline execution.
Separar em `StartTime` e `FinalTime`?

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +	Timestamp   int64                  `json:"timestamp" bson:"timestamp,omitempty"`     // Timestamp of pipeline execution.
usar `time.Time` ?

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +	StartTime   int64     `json:"start" bson:"start,omitempty"`             // Timestamp at start of stage.
usar `time.Time`?

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +	FinalTime   int64     `json:"end" bson:"end,omitempty"`                 // Timestamp at the end of stage.
usar `time.Time`?

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +type PipelineResult struct {
[sugestão] ter um campo aqui que indique se o pipeline rodou com sucesso ou se houve problema.

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +func (p *Pipeline) Run() (PipelineResult, error) {
Precisa checar se não  há estágios com o mesmo nome. Isso é necessário pois o nome do estágio é a forma de indexar os resultados.

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +		if err := buildImage(id, dir, stage.BuildEnv, &ser.BuildResult); err != nil {
Eu acho que não existe uma regra definida. Essa é uma característica herdada do C e lá era usada principalmente em dois casos:

- Quando queria retornar o erro e mais outro valor. Go resolveu esse problema permitindo que se retornem múltiplos valores e tornando erro um tipo. Em go, esse é o caso mais comum e pode ser visto em [http.Get](https://golang.org/pkg/net/http/#Client.Get)
- Quando era importante para a chamadora da função controlar a criação do objeto do objeto. Em go, esse é o caso de [json.Unmarshal](https://golang.org/pkg/encoding/json/#Unmarshal)

Como sugestão, nesse caso eu retornaria o `BuildResult` por esse ser mais simples de entender e não haver a necessidade de controle por parte da chamadora.

2020-07-14 12:02 UTC, danielfireman commented on pipeline.go
> +	if status.Code(result.ExitStatus) != status.OK {
Analisei essa parte novamente e acho que, uma vez que você retorna a struct que contém toda informação, essa checagem deve ser feita na função chamadora (no loop). Isso vai tornar mais diretas as opções de retorno.

Atualmente:

Temos o caso em que retornamos erro e você ainda deve utilizar a `Result` retornada (isso deve ser evitado pois em geral o idioma go é checar erro e, caso diferente de nil, ignorar o valor de retorno). Nesse caso, mesmo `CmdResult` sendo passada como referência, ainda é considerado retorno pois está sendo completamente preenchida nesse método.

Sugestão:

O erro da linha 164 não está sendo checado (problema). Ele deve ser checado e as funções `buildImage`e `runImage` só devem retornar erro quando a execução do comando der erro. Nesse caso, o `Result` não será preenchido. Caso o comando execute sem problemas, o `Result` é preenchido e o erro retornado é nil. Assim temos o erro e o retorno sendo mutuamente exclusivos, o que é bastante desejado.

Note que quando o comando der erro temos que criar um `CmdResult` especial, indicando que o  comando não foi nem executado, logo, não tem saída padrão, nem saída de erro e nem status.

2020-07-16 13:40 UTC, Lorenaps commented on pipeline.go
> +		if err := buildImage(id, dir, stage.BuildEnv, &ser.BuildResult); err != nil {
Certo. Fiz as alterações.

2020-07-16 13:40 UTC, Lorenaps commented on pipeline.go
> +	StageResult []StageExecutionResult `json:"stageResult" bson:"stageResult,omitempty"` // Results of stage execution.
Nesse caso não seria melhor StagesResults?

2020-07-16 13:51 UTC, Lorenaps commented on pipeline.go
> +	StartTime   int64     `json:"start" bson:"start,omitempty"`             // Timestamp at start of stage.
Eu estava pensando em retornar o timestamp mesmo, sem formatação, assim quem consumir formata como quiser. O que acha?

2020-07-16 13:52 UTC, Lorenaps commented on pipeline.go
> +type PipelineResult struct {
Adicionei.

2020-07-16 13:53 UTC, Lorenaps commented on pipeline.go
> +func (p *Pipeline) Run() (PipelineResult, error) {
Concordo contigo. Vou abrir uma issue pra isso. Priorizar agora os demais ajustes. Tudo bem?

2020-07-16 13:53 UTC, Lorenaps commented on pipeline.go
> +	Timestamp   int64                  `json:"timestamp" bson:"timestamp,omitempty"`     // Timestamp of pipeline execution.
Feito.

2020-07-16 13:53 UTC, Lorenaps commented on pipeline.go
> +	Timestamp   int64                  `json:"timestamp" bson:"timestamp,omitempty"`     // Timestamp of pipeline execution.
Eu estava pensando em retornar o timestamp mesmo, sem formatação, assim quem consumir formata como quiser. O que acha?

2020-07-16 17:54 UTC, danielfireman commented on pipeline.go
> +func (p *Pipeline) Run() (PipelineResult, error) {
Tudo certo.

2020-07-16 17:56 UTC, danielfireman commented on pipeline.go
> +	StartTime   int64     `json:"start" bson:"start,omitempty"`             // Timestamp at start of stage.
Então, `time.Time` também te dá essa possibilidade em Go. A diferença é que ele também carrega consigo informações sobre timezone.

O serializador JSON de go já sabe lidar bem e de forma transparente com `time.Time` (da mesma forma os BDs). Usando timestamp, você apenas vai ter o trabalho de converter para `UnixTime()` que é  o timestamp.

2020-07-16 17:57 UTC, danielfireman commented on pipeline.go
> +	Timestamp   int64                  `json:"timestamp" bson:"timestamp,omitempty"`     // Timestamp of pipeline execution.
Respondi abaixo.

2020-07-16 17:58 UTC, danielfireman commented on pipeline.go
> +	StageResult []StageExecutionResult `json:"stageResult" bson:"stageResult,omitempty"` // Results of stage execution.
A tradução para inglês de "resultados dos estágios" é "stage results".

2020-07-16 18:56 UTC, Lorenaps commented on pipeline.go
> +	StageResult []StageExecutionResult `json:"stageResult" bson:"stageResult,omitempty"` // Results of stage execution.
Certo.

2020-07-16 19:21 UTC, Lorenaps commented on pipeline.go
> +	StartTime   int64     `json:"start" bson:"start,omitempty"`             // Timestamp at start of stage.
Bacana. Eu tentei fazer a alteração e ele não permite salvar o formato do Unix() para um time.Time. 
Não achei o UnixTime().
```
var t time.Time

t = time.Now().Unix()
```

2020-07-16 21:15 UTC, Lorenaps commented on pipeline.go
> +			Cmd:        strings.Join(cmdList, " "),
Com relação ao retorno, você acha que podemos deixar apenas o `ExitStatus` ou faz sentido manter os outros e adiciona o Env, talvez?

2020-07-16 21:16 UTC, Lorenaps commented on pipeline.go
> +	StartTime   int64     `json:"start" bson:"start,omitempty"`             // Timestamp at start of stage.
Alterei para utilizar time.Time.

2020-07-16 21:16 UTC, Lorenaps commented on pipeline.go
> +	if status.Code(result.ExitStatus) != status.OK {
Certo. Fiz os ajustes.

2020-07-16 23:20 UTC, danielfireman commented on pipeline.go
> +			Cmd:        strings.Join(cmdList, " "),
Depois da nossa conversa pelo slack, de ter lido com mais cuidado a documentação (obrigado por ter trazido esse assunto) e de ter olhado o código do loop acima, acho que nesse caso é um poquinho mais complicado. 

Acho que tem que ter um [switch de tipos](https://tour.golang.org/methods/16) aqui. Caso seja `exec.Error`, temos que retornar esse erro e o cmd por ser nil, pois ele vai ser ignorado (o loop acima está certinho). Caso seja `exec.ExitError`, não faz nada e pode seguir para a linha 249 e retornar nil no error. 

Para ilustrar, [esse snippet](https://play.golang.org/p/1Y4jN0_h2oK) do go playground mostra um ExitError (comando chamado errado) e [esse](https://play.golang.org/p/m9G9RdGnfhv) um `exec.Error` (comando que não existe)

2020-07-17 18:42 UTC, Lorenaps commented on pipeline.go
> +			Cmd:        strings.Join(cmdList, " "),
Beleza! Adicionei o switch para a opção `exec.Error` mas não para a `exec.ExitError` visto que, nesse caso, a ideia dessa era seguir para a linha 249.

2020-07-17 20:10 UTC, danielfireman approved these changes

2020-07-21 15:12 UTC, merged